[project]
name = "ethio-data"
version = "0.1.0"
description = "Data projects for Ethiopia"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.4",
]
